platform :ios, '12.0'

use_frameworks!

target 'AVFoundationHelperRx_Example' do
  pod 'AVFoundationHelperRx', :path => '../'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  target 'AVFoundationHelperRx_Tests' do
    inherit! :search_paths
  end
end
